spring.application.name=gateway-service
spring.main.web-application-type=reactive
server.address=0.0.0.0
server.port=8080

# Logging
logging.level.root=DEBUG
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=DEBUG
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework=DEBUG

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

# 0 - Authentication Service Routes
spring.cloud.gateway.routes[0].id=authentication
spring.cloud.gateway.routes[0].uri=lb://zcare-authentication
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/users(?<segment>/?.*),/v1/users${segment}

# 1 - Station Service Route
spring.cloud.gateway.routes[1].id=stations-service
spring.cloud.gateway.routes[1].uri=lb://stations-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/stations/**

# 2 - Zwash Service Provider
spring.cloud.gateway.routes[2].id=zcare-service-provider
spring.cloud.gateway.routes[2].uri=lb://zcare-service-provider
spring.cloud.gateway.routes[2].predicates[0]=Path=/service-provider/**

# 3 - Booking Service Route
spring.cloud.gateway.routes[3].id=booking-service
spring.cloud.gateway.routes[3].uri=lb://zcare-booking
spring.cloud.gateway.routes[3].predicates[0]=Path=/booking/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/booking,/v1/bookings

# 4 - Car Management Service Route
spring.cloud.gateway.routes[4].id=car-management-service
spring.cloud.gateway.routes[4].uri=lb://zcare-car-management
spring.cloud.gateway.routes[4].predicates[0]=Path=/cars/**
